import Head from 'next/head'
import Image from 'next/image'
import Videodownloader from "../old_pages/Video/Video"

export default function Home() {
  return (
    <div className="parentDiv">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Videodownloader/>
      
    </div>
  )
}
